In [132]:
import numpy as np

In [133]:
def generateKeyMatrix(key):
    keyMatrix = np.zeros((3, 3), dtype=int)
    index = 0

    for i in range(3):
        for j in range(3):
            keyMatrix[i, j] = ord(key[index]) - ord('a')
            index += 1

    return keyMatrix

In [144]:
def generateMessageMatrix(message):
    messageMatrix = np.zeros((3, 196), dtype = int)
    index =0

    for i in range(196):
        for j in range(3):
            messageMatrix[j, i] = ord(message[index]) - ord('a')
            index += 1
    return messageMatrix

In [135]:
# Example usage:
# Assuming you have the plainMatrix and keyMatrix already defined as NumPy arrays
# plainMatrix = np.array([[...], [...], [...]])  # Shape: (3, 196)
# keyMatrix = np.array([[...], [...], [...]])    # Shape: (3, 3)
# encryptedMatrix = encrypt(plainMatrix, keyMatrix)
def encrypt(plainMatrix, keyMatrix):
    encryptedMatrix = np.zeros((3, 196), dtype=int)

    for i in range(3):
        for j in range(196):
            encryptedMatrix[i, j] = np.sum(keyMatrix[i] * plainMatrix[:, j]) % 26

    return encryptedMatrix

In [136]:
def matMult(A, B):
    ans = B @ A

    return ans%26

In [137]:
# matrix_3x3 = np.array([[1, 2, 3],
#                        [4, 5, 6],
#                        [7, 8, 9]])

# # 3x4 matrix
# matrix_3x4 = np.array([[11, 12, 13, 14],
#                        [15, 16, 17, 18],
#                        [19, 20, 21, 22]])
# matMult(matrix_3x4, matrix_3x3)

In [138]:
encryptedText = "qul zonuw arzbda ikbnrl qul gbjz, ufgaxo gv llzl, mena … ml pyxxgl t rapobezx cevf xozhihax kbaafan zlq pl kba gbpllpnyr. xys mena bp alxark tor aab yhpp bm gxgbkb. … [gotq vz,] meryx znu axil ubru t yvn uxan vorhmfbu pfgohrg aab ulem bm zlq, wklipwbq aab yhpp bm gxgbkb cyx-anax qul nkvcxofl. hre jhkpliq bm mfzl ubtpgp jpme gox zeltqvvg ls aab hubsrylb. goxormhor py qul exjz hc ahmrel vorhmbq aab hubsrylb, goxpr sttf tnpg otsr lqffaxa cyble ah qvtx; quhm ff aab yhpp bm gxgbkb jvniq ix lhalfql hc gpfb. jotq jl axil meru bp gvmxysr kbu-ielzbzns exjz, hrgzbar vy qvtx, zeltqvuz x hubsrylb. avp quhm arzvovwmfbu fftom pbbga fvfbjotq shffypto. ilkv zbve ypdb gox yviefphe zbuvbca hc tvw: kba ielzbzns, hrgzbar vy qvtx, xosx qb jkbnax  rapobezx";

In [139]:
encryptedText = "".join(c for c in encryptedText if c.isalpha())

In [140]:
key = 'abcdefghi'

In [141]:
km = generateKeyMatrix(key)

In [142]:
km

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
mm = generateMessageMatrix(encryptedText)
mm

array([[16, 25, 20, 17,  3, 10, 17, 20,  1, 20,  0,  6, 11, 12,  0, 15,
        23, 19, 15,  4,  2,  5, 25,  7, 10,  0, 13, 16, 10,  6, 11, 13,
        23, 12,  0,  0,  0, 19,  0, 24, 15,  6,  1,  6, 16, 12, 24, 13,
        23, 20, 20, 21, 23, 21,  7,  1,  5,  7,  0, 20, 12, 25, 22,  8,
         1,  0,  7,  1, 23, 10, 24, 13, 16, 13,  2,  5, 17,  7, 11,  1,
         5, 20, 15,  9,  4, 23, 11, 21, 11,  0, 20, 17,  1, 23, 12, 17,
        16,  4, 25,  0, 17, 21,  7, 16,  1,  1, 24,  6, 15, 19, 19,  6,
        18, 16,  0,  2, 11,  7, 19, 20,  5,  0,  7,  1, 23, 10, 21, 16,
        11, 11, 11,  6,  1, 19, 11,  8,  4,  1, 21, 24, 10,  8, 25, 13,
        23,  7, 25, 17, 16, 23, 11, 21, 23,  1, 24,  0, 16, 12, 25, 21,
         5,  5, 14,  1,  0,  5, 14, 18,  5, 19, 11, 25,  4,  3, 14, 21,
         5,  4, 20,  2,  2, 22,  0, 11, 25,  7, 25, 17, 16, 23, 18,  1,
         1, 23, 15,  4],
       [20, 14, 22, 25,  0,  1, 11, 11,  9,  5, 23, 21, 25,  4, 12, 24,
         6, 17, 14, 25,  4, 23,  7,  0,

In [152]:
ct = encrypt(mm, km)

In [153]:
k_inv = np.linalg.inv(km)
k_inv = k_inv.astype(int)%26

LinAlgError: Singular matrix

In [154]:
ct

array([[16, 14, 22,  1, 16,  1, 17, 23,  7, 17, 25, 17, 21,  4,  8, 18,
         2, 17, 16, 19, 20, 25, 23, 20,  1,  5, 21, 11,  1,  5, 15,  6,
         8,  4,  5,  5, 11, 22,  2, 11, 25,  9, 12,  0, 19, 12, 21, 20,
         4,  9, 15,  1,  0, 22, 22, 24,  8,  3,  2, 19, 25, 17,  6,  7,
        16, 23, 19, 24,  8,  5, 23, 20, 16,  0, 25, 25, 22, 14, 14, 10,
        21, 13, 10, 13,  8,  7, 25,  7, 18, 15, 11, 20,  8, 22,  9, 11,
        16, 15, 11,  5,  0, 22, 14,  0, 21,  0, 13,  8,  1,  3, 17,  0,
        13, 15, 23,  0,  4,  6,  3,  5,  5, 23, 19, 24,  8, 19,  3,  2,
         7, 11, 11, 25, 11,  8, 20,  9,  5,  1,  6,  0, 15,  0, 25,  0,
         7,  3,  1, 17,  7,  7, 25, 18, 21,  0, 13, 25,  8,  8, 23, 20,
        15, 17, 16, 13, 21, 19, 25, 17,  2,  4,  0, 17,  2, 13, 19, 16,
         3,  1, 23, 14,  9, 12, 16,  1, 23,  3,  1, 17,  7, 25,  3,  3,
        13, 17, 16, 19],
       [ 1, 14, 18,  0, 23, 21, 19,  4,  8,  6,  6,  1,  6, 13, 25, 22,
        18, 21,  2, 19, 23, 21, 13,  6,

In [155]:
ct.tolist()

[[16,
  14,
  22,
  1,
  16,
  1,
  17,
  23,
  7,
  17,
  25,
  17,
  21,
  4,
  8,
  18,
  2,
  17,
  16,
  19,
  20,
  25,
  23,
  20,
  1,
  5,
  21,
  11,
  1,
  5,
  15,
  6,
  8,
  4,
  5,
  5,
  11,
  22,
  2,
  11,
  25,
  9,
  12,
  0,
  19,
  12,
  21,
  20,
  4,
  9,
  15,
  1,
  0,
  22,
  22,
  24,
  8,
  3,
  2,
  19,
  25,
  17,
  6,
  7,
  16,
  23,
  19,
  24,
  8,
  5,
  23,
  20,
  16,
  0,
  25,
  25,
  22,
  14,
  14,
  10,
  21,
  13,
  10,
  13,
  8,
  7,
  25,
  7,
  18,
  15,
  11,
  20,
  8,
  22,
  9,
  11,
  16,
  15,
  11,
  5,
  0,
  22,
  14,
  0,
  21,
  0,
  13,
  8,
  1,
  3,
  17,
  0,
  13,
  15,
  23,
  0,
  4,
  6,
  3,
  5,
  5,
  23,
  19,
  24,
  8,
  19,
  3,
  2,
  7,
  11,
  11,
  25,
  11,
  8,
  20,
  9,
  5,
  1,
  6,
  0,
  15,
  0,
  25,
  0,
  7,
  3,
  1,
  17,
  7,
  7,
  25,
  18,
  21,
  0,
  13,
  25,
  8,
  8,
  23,
  20,
  15,
  17,
  16,
  13,
  21,
  19,
  25,
  17,
  2,
  4,
  0,
  17,
  2,
  13,
  19,
  16,
  3,
  1,
  23,
 

In [156]:
cT = ''.join(chr(ct[j][i] + ord('a')) for i in range(196) for j in range(3))

In [157]:
cT

'qbmooowsobazqxebvprtvxelhijrgvzgnrblvgrenwizqswacsirvzqcotttuxazvrxndugsbipfujvmdlhdbipfthpwdgmsivienwfbxfdblorwqkcfiltbzfljklmwganatxbmhcvdlupkeawjtdpwdbhnaeiwwwwqkycgifcdpbcfituvzwtrrrgfehmrqpoxurtahydiiugfsfxituycqbmacezmzzqhwiuogyopqkhevohndtkosnrvicwhhhzhphvjsbkpnllyluuuitewcijezlxjqbmptxljhfkpaskwwwoweawsvbhaeinrvihgbvpdcbrcnananvdpppxofadgexqgikdvnfsffjnxurtahydiiugtbjdzvcnyhjlldvltbzzzlfzikmusqjynfyrbpdgseavqpetarizwtabchwldpbbbbrvzhtfhhhzhpsiyvpjaeinrvzdhihgiraxvtudmppprajqjcnljvvvtmfzqhrdpcegexqawsrcncbanrvtuvqlgdgjbnzxtpopqjfbmhcqakbipxjvdpbbbbrvzhtfzxvdshdltndtrhxqcottt'

In [125]:
chr(ct[0][0])

'\x10'